# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates weekly
    schedule:
      interval: 'weekly'
      day: 'friday'
    # Basically no limit
    open-pull-requests-limit: 50
