name: Run CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 24
          - 26
    name: Node ${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: pnpm/setup@c9883cc79df532ad1a7b81bf9ab944ceb090d65c # v2.0.0
        with:
          runtime: 'node@${{ matrix.node-version }}'

      - name: Check code style
        run: |
          pnpm fmt
          git --no-pager diff --exit-code

      - name: Build # Type checking
        run: pnpm build

      - name: Test
        run: pnpm test
