name: Run CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 22
          - 24
          - 25
          - 26
    name: Node ${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1.0.0
        with:
          runtime: 'node@${{ matrix.node-version }}'

      - name: Check code style
        run: |
          pnpm fmt
          git --no-pager diff --exit-code

      - name: Build # Type checking
        run: pnpm build

      - name: Test
        run: pnpm test
