name: Publish Package to npmjs
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          runtime: node@26.8.1
      - run: pnpm build
      - name: Ensure clean working tree
        run: git --no-pager diff --exit-code
      - run: pnpm clean-package -- ava packageManager devDependencies scripts
      - run: pnpm stage publish --access public --provenance --no-git-checks
