name: Update dependencies

on:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:
  update:
    uses: melusc/workflows/.github/workflows/update-dependencies.yml@main
    secrets:
      cprToken: ${{ secrets.CPR_TOKEN }}
